spring:
  application:
    name: food-ordering-system

  datasource:
    url: jdbc:postgresql://localhost:5432/food_order_system_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: myverysecurejwtsecretkey1234567890123456789012