spring:
  application:
    name: food-ordering-system

  #  database config
  datasource:
    url: jdbc:postgresql://localhost:5432/food_order_system_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  #  mail config
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #   jpa config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 976496236052-kr0clk8ovkujnaod8faf7li9e8o6o2ce.apps.googleusercontent.com      # Get this from Google Cloud Console
            client-secret: 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
            scope:
              - profile
              - email
              - openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

# jwt config
jwt:
  secret: myverysecurejwtsecretkey1234567890123456789012

app:
  frontend-base-url: http://localhost:5173
  token-expiration-hours: 48
  oauth2:
    redirect-success-uri: http://localhost:5173/oauth2/callback